# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ public ]
  pull_request:
    branches: [ public ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Angular Build
      run: npm run -- build --prod --base-href=/misconceptions-lab-ui/ --crossOrigin=use-credentials
    - name: Upload Artifact
      if: ${{ matrix.node-version == '12.x' }}
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/returnOfTheJulian/
  
  deploy:
    needs: build
    # Only deploy on commits to master, not pull requests
    if: ${{ github.event_name == 'push' }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: PWD
        run: pwd
      - name: Display structure of downloaded files
        run: ls -R
      - name: rsync Deploy
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete
          remote_path: ${{ secrets.DEPLOY_PATH_PUBLIC }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
